apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nominatim
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: nominatim
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
