kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
  namespace: nominatim
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
parameters:
  skuName: Standard_LRS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nominatim-bd-arg
  namespace: nominatim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 10Gi 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nominatim
  namespace: nominatim
spec:  
  selector:
    matchLabels:
      app: nominatim
  serviceName: "nominatim"
  replicas: 1 
  template:
    metadata:
      labels:
        app: nominatim
    spec:
      terminationGracePeriodSeconds: 5
      volumes:
        - name: nominatim-bd-arg
          persistentVolumeClaim:
            claimName: nominatim-bd-arg
      containers:
        - name: nominatim
          image: cquirogaRegistry.azurecr.io/nominatim-arg
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 5432
          command: ["sh", "/app/init.sh"]
          volumeMounts:
            - name: volumen
              mountPath: /data
            - name: nominatim-bd-arg
              mountPath: /dataazure
          resources:
            requests: # minimum resources required
              cpu: 250m
              memory: 64Mi
            limits: # maximum resources allocated
              cpu: 1500m
              memory: 1512Mi

  volumeClaimTemplates:
  - metadata:
      name: volumen
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
