kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
  namespace: nominatim
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
parameters:
  skuName: Standard_LRS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nominatim-bd-arg
  namespace: nominatim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 10Gi 
---
apiVersion: v1
kind: Job
metadata:
  name: nominatim
  namespace: nominatim
spec:
  containers:
    - name: nominatim
      image: cquirogaRegistry.azurecr.io/nominatim-arg
      imagePullPolicy: Always
      command: ["sh", "/app/initJob.sh"]
      resources:
        requests:
          cpu: 250m
          memory: 128Mi
        limits:
          cpu: 1500m
          memory: 1512Mi
      volumeMounts:
      - mountPath: /dataazure
        name: azurefile
  volumes:
    - name: azurefile
      persistentVolumeClaim:
        claimName: azurefile
